# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [72]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np
print(pd.__version__)

2.3.3


## Regression Model Evaluation

In [75]:
column_names = ['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT','MEDV']
housing_df = pd.read_csv('housing.csv', header=None, delimiter=r"\s+", names=column_names)

X_h = housing_df.drop("MEDV", axis=1)
y_h = housing_df["MEDV"]

In [34]:
"""
CRIM - per capita crime rate by town
ZN - proportion of residential land zoned for lots over 25,000 sq.ft.
INDUS - proportion of non-retail business acres per town.
CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)
NOX - nitric oxides concentration (parts per 10 million)
RM - average number of rooms per dwelling
AGE - proportion of owner-occupied units built prior to 1940
DIS - weighted distances to five Boston employment centres
RAD - index of accessibility to radial highways
TAX - full-value property-tax rate per $10,000
PTRATIO - pupil-teacher ratio by town
B - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
LSTAT - % lower status of the population
MEDV - Median value of owner-occupied homes in $1000's"""

"\nCRIM - per capita crime rate by town\nZN - proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS - proportion of non-retail business acres per town.\nCHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)\nNOX - nitric oxides concentration (parts per 10 million)\nRM - average number of rooms per dwelling\nAGE - proportion of owner-occupied units built prior to 1940\nDIS - weighted distances to five Boston employment centres\nRAD - index of accessibility to radial highways\nTAX - full-value property-tax rate per $10,000\nPTRATIO - pupil-teacher ratio by town\nB - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT - % lower status of the population\nMEDV - Median value of owner-occupied homes in $1000's"

In [74]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [76]:
#< 0.8 gives True for ~80% of rows, False for ~20%. Rows with True are the training set. Rows with False are the test set.
Xtr_h, Xte_h, ytr_h, yte_h = train_test_split(X_h, y_h, test_size=0.2, random_state=42)
print("Housing — training set:", Xtr_h.shape, ytr_h.shape)
print("Housing — test set    :", Xte_h.shape, yte_h.shape)

Housing — training set: (404, 13) (404,)
Housing — test set    : (102, 13) (102,)


## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [77]:
housing_model = LinearRegression()
housing_model.fit(Xtr_h, ytr_h)

print("Housing Intercept:", housing_model.intercept_)
print("Housing Coefficients:", housing_model.coef_)

Housing Intercept: 30.24675099392351
Housing Coefficients: [-1.13055924e-01  3.01104641e-02  4.03807204e-02  2.78443820e+00
 -1.72026334e+01  4.43883520e+00 -6.29636221e-03 -1.44786537e+00
  2.62429736e-01 -1.06467863e-02 -9.15456240e-01  1.23513347e-02
 -5.08571424e-01]


## 3. Calculate and print R-squared for both the training and the testing set.

In [79]:
ytr_h_pred = housing_model.predict(Xtr_h)
yte_h_pred = housing_model.predict(Xte_h)

print("Housing Training R²:", r2_score(ytr_h, ytr_h_pred))
print("Housing Test R²    :", r2_score(yte_h, yte_h_pred))


Housing Training R²: 0.7508856358979673
Housing Test R²    : 0.6687594935356347


## 4. Calculate and print mean squared error for both the training and the testing set.

In [80]:
print("Housing Test MSE   :", mean_squared_error(yte_h, yte_h_pred))
print("Housing Test MAE   :", mean_absolute_error(yte_h, yte_h_pred))

Housing Test MSE   : 24.291119474973325
Housing Test MAE   : 3.189091965887816


## 5. Calculate and print mean absolute error for both the training and the testing set.

In [40]:
print("Mean absolute error: %.2f" % np.mean(np.absolute(test_y_ - test_y)))
print("R2-score: %.2f" % r2_score(test_y , test_y_))


Mean absolute error: 3.01
R2-score: 0.70


## Classification Model Evaluation

In [81]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression

iris = load_iris()
print(iris.DESCR[:600], '...')

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ====  ...


In [82]:
X_i = iris.data     # shape (150, 4)
y_i = iris.target   # shape (150,)

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [83]:
Xtr_i, Xte_i, ytr_i, yte_i = train_test_split(X_i, y_i, test_size=0.2, random_state=42)
print("Iris — training set:", Xtr_i.shape, ytr_i.shape)
print("Iris — test set    :", Xte_i.shape, yte_i.shape)

Iris — training set: (120, 4) (120,)
Iris — test set    : (30, 4) (30,)


## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [84]:
logreg = LogisticRegression(max_iter=200)
logreg.fit(Xtr_i, ytr_i)





LogisticRegression(max_iter=200)

In [85]:
# Sanity check
print("Has coef_ after fit?", hasattr(logreg, "coef_"))

print("LogReg intercept   :", logreg.intercept_)
print("LogReg coefficients:\n", logreg.coef_)

Has coef_ after fit? True
LogReg intercept   : [  9.01155696   1.86769398 -10.87925094]
LogReg coefficients:
 [[-0.3938084   0.96217921 -2.37520163 -0.99872916]
 [ 0.50856201 -0.25477594 -0.21286761 -0.77576759]
 [-0.11475361 -0.70740327  2.58806925  1.77449675]]


## 8. Calculate and print the accuracy score for both the training and the testing set.

In [86]:
ytr_i_pred = logreg.predict(Xtr_i)
yte_i_pred = logreg.predict(Xte_i)

print("Iris train accuracy:", accuracy_score(ytr_i, ytr_i_pred))
print("Iris test accuracy :", accuracy_score(yte_i, yte_i_pred))

Iris train accuracy: 0.975
Iris test accuracy : 1.0


## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [88]:
# balanced accuracy score for both training and test sets
from sklearn.metrics import balanced_accuracy_score
print("Iris train balanced accuracy:", balanced_accuracy_score(ytr_i, ytr_i_pred))
print("Iris test balanced accuracy :", balanced_accuracy_score(yte_i, yte_i_pred))


Iris train balanced accuracy: 0.975609756097561
Iris test balanced accuracy : 1.0


## 10. Calculate and print the precision score for both the training and the testing set.

In [89]:
# precision score for both training and test sets
from sklearn.metrics import precision_score
print("Iris train precision score:", precision_score(ytr_i, ytr_i_pred, average='macro'))
print("Iris test precision score :", precision_score(yte_i, yte_i_pred, average='macro'))

Iris train precision score: 0.9761904761904763
Iris test precision score : 1.0


## 11. Calculate and print the recall score for both the training and the testing set.

In [92]:
# recall score for both training and test sets
from sklearn.metrics import recall_score
print("Iris train recall score:", recall_score(ytr_i, ytr_i_pred, average='macro'))
print("Iris test recall score :", recall_score(yte_i, yte_i_pred, average='macro'))

Iris train recall score: 0.975609756097561
Iris test recall score : 1.0


## 12. Calculate and print the F1 score for both the training and the testing set.

In [93]:
# f1 score for both training and test sets
from sklearn.metrics import f1_score
print("Iris train f1 score:", f1_score(ytr_i, ytr_i_pred, average='macro'))
print("Iris test f1 score :", f1_score(yte_i, yte_i_pred, average='macro'))

Iris train f1 score: 0.974996093139553
Iris test f1 score : 1.0


## 13. Generate confusion matrices for both the training and the testing set.

In [94]:
# confusion matrix for both training and test sets
from sklearn.metrics import confusion_matrix
print("Iris train confusion matrix:\n", confusion_matrix(ytr_i, ytr_i_pred))
print("Iris test confusion matrix :\n", confusion_matrix(yte_i, yte_i_pred))

Iris train confusion matrix:
 [[40  0  0]
 [ 0 38  3]
 [ 0  0 39]]
Iris test confusion matrix :
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

In [ ]:
# Have fun here !